---
# tasks file for roles/launch_app
- name: Launch my app
  docker_container:
    name: my-api
    image: fabrikot/tp-devops-simple-api
    restart_policy: always
    ports:
      8080:8080
    networks:
      - name: my-network
    state: started
