---
# tasks file for roles/launch_front
- name: Launch my front
  docker_container:
    name: front
    image: tploix/tp-devops-front-server:latest
    restart_policy: always
    ports:
      - 90:90
    networks:
      - name: my-network
    state: started