---
# tasks file for roles/launch_db
- name: Launch my db
  docker_container:
    name: my-db
    image: fabrikot/tp-devops-database
    restart_policy: always
    ports:
      5432:5432
    networks:
      - name: my-network
    volumes:
      - db-volume:/var/lib/postgresql/data
    state: started
